language: php

php:

    - 7.0
    - 7.1
    - nightly
    - hhvm
    - hhvm-nightly

matrix:
    fast_finish: true
    allow_failures:
        - php:
            - 7.0
            - nightly
            - hhvm
            - hhvm-nightly

before_script:
    - composer install --ignore-platform-reqs

script:
    - phpunit
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpcs --standard=codestandard.xml src
