language: php

php:

    - 7.0
    - 7.1
    - nigtly
    - hhvm
    - hhvm-nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: 
            - 7.0
            - nigtly
            - hhvm-nightly

before_script:
    - composer install

script:
    - phpunit
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpcs --standard=codestandard.xml src
